version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://13.201.249.246:5000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
